### ISSUE TITLE
severe voting feature

### ISSUE THREAD

**Issue by vrohatgi** [vrohatgi/Wander#6]
add multiple places and randomly vote gets selected and gives -1 votes

**Comment by srohatgi** [comment]
how many places do we need to add?

**Comment by vrohatgi** [comment]
over 5

**Comment by srohatgi** [comment]
can you attach a screen shot?

**Comment by vrohatgi** [comment]
![screen shot 2017-08-10 at 8 47 04 pm](https://user-images.githubusercontent.com/13690558/29200795-251050e2-7e0d-11e7-8993-085aa6c96ef4.png)

**Comment by srohatgi** [comment]
can we stop people from selecting more than 4 places in an event?

**Comment by vrohatgi** [comment]
*5

**Comment by vrohatgi** [comment]
and that wont solve the problem

**Comment by vrohatgi** [comment]
![screen shot 2017-08-10 at 8 50 46 pm](https://user-images.githubusercontent.com/13690558/29200845-a8a53fa8-7e0d-11e7-99c3-4a8d7b65ccce.png)
